diaspora_user:	"carolina@wk3.org"
guid:  "ef50665184416acf"
server:	"wk3.org"
private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKAIBAAKCAgEA+TRylmCUFJa48ShLUGo/4/EjuDdx6So8gOuaBrX979ym5Y0M
      T7jH1IpUT05CFGLtEzILUceaWStLWQUbNPimR86MFuFbjoy5EHiTBuyVvEVjCedm
      19ZYcsBMtJGnvaNNWRSvhx6zimuTuiy45p9xs0Co9PBkq8E+yfGhcha5OX5olJJB
      op7n7VRSbTjcuPO7DhGjBWf8KgDcTndJK9q4aQ/B2BiVtNHyNjakP9lK2VBSlpra
      wo8GQSxf7DJT0EO+YC44pzbHjhlW+EOb/45ergFL5Xi8R6x+QCGgczVoLc5GHRgI
      AqVnkwUfUAc6XJILFHWPAnkRdzqnEK4FLfDRUkOF6sT58IeeB6ibNxzmJnaLlD2F
      uR1wBYuIHkK91rhjVjn1iZdSHbKLMaqBd8JCeaEM1jXWMAiav/evbr1WwxPviBJy
      HvO5qhlKR+HE5vXTps2IB04ulgciYmrRPSWmJsi00g0GL3pKsG/oJCQOZHXLcDCi
      oJmr3EkPdf0XYF8zskxfPsXnILxJq6M2/BAG5t1qOoErNgGJLvA28VXk3ZM/EdEY
      qoTBSljYGwaNGJEnZSSF3qQovGqu41iY3q/9PlWJFXpdm774QCgJBZO6txHWo/jV
      pPQmLnUvHrkPpyuEtJ0k3pqIqQHEO9IAZaJPizlCUKyNpG6EbwUBAwg2ruUCAwEA
      AQKCAgB7JOiu2KC0H9raCIBXB3n06JcvE+7tOlrVlhbx1ALdAZtTecSorHXK2GRb
      IB/VNSFTx/oB+nGSOKuuHLDaFzkL6MwfDlOQ+IcG1Z5J4KUJePw8y6VtaNUiN1Zw
      MD3Enyq8p1Upnwk3kHtal3jzNb0YyA31o8kLep3NauLNnt7+wzFooXFfq8iN5Yop
      wNyJZJ99j0eQh1b7Zpt3BskYq6dO+2NdpqBrzwcytQOrLXQoOOHm3DTXyZdco1Hv
      RNtX4fH0U0LZll88H9dzLO2sdizhLXDUvznC7UEh7bv80lpdsD3DaLmknRm2c+SK
      RlgXoG9rN8Boh20TDt+5hVS34/V7CJDdRdCG6Vb4j2gLQzLyt250rPjOd0iA5hwV
      1FlYjsjLfWyJTkC4HizEPwsbYGleA/XolaPhpz24JLoBc4HFC13U4cW+oMIxYjb+
      O03Q3Y/bXv4ReXRupM7TXtetpw5kCbssxbue5kF99b7RedcPoTFaAfM5qmkxT7RM
      Kp3Bpk84UBPZKDxkbKj7hPAjJZPDHVK1ggbagS+HJslvjBlHP939I3giqihx5R8A
      fuNt3Wsg/oIK+vGMYJMziLtfur1zI+m6vA00rOfTkkiX1yrSAHXO76sSj9J2XzRc
      kyu4rl1Wl5JtoGuq6GWY5PhlCh8dhCxIVRRUbqxiXw9omzILwQKCAQEA/zXmlFTb
      /y7CQ3TWKCvU/pgzAfo7Glj3BxBIpoEyDfpUGQkOQclV53H2/TQg5naCPXWQjuf1
      r2I+9dtiDaerabxkAv9BCXgpBKXUgt+LYHoposWj484Cx4fQeoCqVXxn6rqNfgTd
      NTdZ5ch89t3ruAenD2W7PBME33AvgTRsreLrJxBVIZ+M4CEuXXAtmMdKHJqXMYme
      te2+9SJxa7KUgP6SuJtkadtAUnPcXYbaOeVT/VFpZ1X2VHsD7OSlbDZI4aTjzA8i
      rUTKLVR5IoNwKhXEfd/8ipOdpOxgIyVsKv8M8//lRkjmqm5wkhqRGhinOp2n6jSv
      gfGVR0zofV2TdQKCAQEA+fnKgrMAvXo4W2Hx2ctOeDfV2aGNJC4hMR54Vkb1uK8D
      CzmAVOjci2beJM41n09+Ffktg5uaiMgR0DlTXiawav5DV9g8bg47YUT6z5Bi/sV8
      culnOLgtK7AJ0a7R0zzb3oNyAzIzQoj0COdyjmxW8Bx4FiM3S3jkXpkSLYy1GeX4
      T9PQ1+j3cgggExHEmEikY3y/oOQC+bpf4EMUoBjqduEdsBxn/bR3lxlxm7B+QMzh
      r+dpummAc5gpSNofvzHjpeQP/fDfjBy8BhI6gIO7VZHX94Zc7/KXwbO3DlHpiJS6
      2sFg7IbQSvO7PuAxpc0cNEF6/Kogx8sqJ2ziGsRvsQKCAQA/kmimiGDotvgTH5Z9
      GTYMWVNTacaxMHoQW2ENgN88FiA+wD+56XIpnfzdY8/SOLEGqDNjNarAjmOKkKRj
      LGIJi7EKAhVsS29ERh6inxaz6JpYfoztoRKWK2GmMki71Kp6ERBP1NxZdjlBgOiI
      Ag3GoLlfn4K9Wyt6kRJ0R9/OjNjwuSPLpVfNONa41cm15eazK1sALvzG6rsHixXf
      svNFEqTvsV2Y9NGX+F5rOb1AcLy0PERaRlJ/Bsmah/Yg94C+HHnWCeskaB9InWMz
      UrRs91Ej3dilmFHLlEn6V0cTisbqPNMa5+v1hl8qNc3xRzTY6A68y3TwlIIP6bt8
      BwRFAoIBAQD45XR0KpNkFhujMaTDvKDHJqExbp/AFIZMCBC9py3m06tuM7TJ1oox
      6xzo/MF7fIUIj/B3iCmYY80IzOtrZY5nGgAnqVCSLG2Hbk1k+lj3X9+H80opuYiQ
      ZVmBhFW7xG8P4UVWVVegughyDTGNCeaOcWpIcIwQA7EvV6432FBCFy7lHPxm3rny
      upBlLF3ZWwsDXCTZp+4mhSINg/03Y1ehQohy3/XTMSuaMWVjJZqwHs/ge8RULdQO
      RMVmmnjdwGjwtmIN8RZExh+Y0/GYIJIYo3ysIwbKi3v7DFwKUBj9O0nJop5FI/6l
      goVAF66XbeDVTxWMGkFFbc7tLob7K/ghAoIBAEuFA2kTesLG8BDEMPTNnTCBy1bH
      TAOQ1CnUkRRvixHem1mFz3XLOPy4yhRRwK1lK5UDP6Lyw8AzMylxcBJMmSRqODbf
      sknok9wRRI/OlhcVyuMJA5zWOGpxr2RLoDstmvcDuMByn7Ri90YJm/DM0bNNpK9U
      uXITDSRubuMgJUSapj+bpbkVoyWxB8HU4h6lwxMyWblJJYefhGZwNbBlsuad0QsJ
      iye9szuNOPhjy51Sbu0dMP6Zw9Yrx5EvVJIDwsZYlfPvUN5WIID6B/Ern7sDuPGi
      F3pFJq3u5fm/ksqUwncA27MHsd/QtVdcD6W0GQp4f2eKVbDkzrBvZNB/YaE=
      -----END RSA PRIVATE KEY-----